"""DK-Mem write-side extraction: one probe utterance -> one ``Extraction``.

The model is prompted with a frozen prompt (default ``mem0_extraction_v1``)
and must return one JSON object with ``gloss``, ``distinction`` and
``surface``. Output is validated strictly: anything malformed raises
``ExtractionError`` carrying the raw response; nothing is repaired or dropped.

``lang_profile`` is derived deterministically from the probe's ``lang`` tag
and the utterance (see ``derive_lang_profile``), never generated by the model.
"""

from __future__ import annotations

import json
import unicodedata
from collections import Counter
from types import MappingProxyType
from typing import Any, Protocol, Sequence

from dkmem.backends.llm import GenerationParams
from dkmem.memory.prompts import (
    MEM0_EXTRACTION_V1,
    MEM0_EXTRACTION_V2,
    MEM0_EXTRACTION_V3,
    PromptTemplate,
)
from dkmem.memory.schema import SIDES, Extraction, ProbeItem

__all__ = [
    "DISTINCTION_KEYS",
    "CLOSED_DISTINCTION_VALUES",
    "ExtractionError",
    "ExtractionBatchError",
    "TextGenerator",
    "utterance_for",
    "parse_model_output",
    "derive_lang_profile",
    "build_extraction",
    "extract",
    "extract_many",
]

_DK_FEATURE_KEYS = frozenset(
    {
        "kinship",
        "register",
        "politeness",
        "evidentiality",
        "classifier",
        "temporal_deixis",
        "name_variant",
    }
)

# Distinction keys each prompt allows (must mirror the prompt text).
DISTINCTION_KEYS = MappingProxyType(
    {
        MEM0_EXTRACTION_V1.prompt_id: _DK_FEATURE_KEYS,
        MEM0_EXTRACTION_V2.prompt_id: _DK_FEATURE_KEYS,
        MEM0_EXTRACTION_V3.prompt_id: _DK_FEATURE_KEYS,
    }
)

# Features whose values the prompt restricts to a closed set.
CLOSED_DISTINCTION_VALUES = MappingProxyType(
    {
        "politeness": frozenset({"formal", "informal"}),
        "evidentiality": frozenset({"direct/confirmed", "reported/hearsay"}),
        "temporal_deixis": frozenset({"yesterday", "tomorrow"}),
    }
)


class ExtractionError(ValueError):
    """Model output (or generator behaviour) that violates the extraction contract."""

    def __init__(
        self,
        message: str,
        *,
        pair_id: str | None = None,
        side: str | None = None,
        raw_output: str | None = None,
    ) -> None:
        where = f"{pair_id}/{side}: " if pair_id is not None else ""
        super().__init__(where + message)
        self.pair_id = pair_id
        self.side = side
        self.raw_output = raw_output


class ExtractionBatchError(ExtractionError):
    """Some items in a batch failed.

    ``extractions`` is aligned with the input (``None`` where an item failed)
    and ``failures`` holds the per-item ``ExtractionError``s, each with its
    raw model output, so nothing generated is lost.
    """

    def __init__(
        self, failures: list[ExtractionError], extractions: list[Extraction | None]
    ) -> None:
        super().__init__(
            f"{len(failures)} of {len(extractions)} extractions failed: "
            + "; ".join(str(f) for f in failures[:3])
            + (" ..." if len(failures) > 3 else "")
        )
        self.failures = failures
        self.extractions = extractions


class TextGenerator(Protocol):
    """What extraction needs from a backend (``HFGenerator`` satisfies it)."""

    @property
    def backbone(self) -> str: ...

    def generate(self, prompts: Sequence[Any], params: GenerationParams | None = None) -> list[str]: ...


def utterance_for(probe: ProbeItem, side: str) -> str:
    """The utterance on ``side`` (``"a"`` or ``"b"``) of a probe."""
    if side not in SIDES:
        raise ValueError(f"side must be one of {SIDES}, got {side!r}")
    return probe.utt_a if side == "a" else probe.utt_b


# --- parsing ----------------------------------------------------------------


def _reject_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    keys = [k for k, _ in pairs]
    dupes = sorted({k for k in keys if keys.count(k) > 1})
    if dupes:
        raise ExtractionError(f"duplicate JSON keys: {dupes}")
    return dict(pairs)


def parse_model_output(
    raw_output: str, *, utterance: str, prompt: PromptTemplate = MEM0_EXTRACTION_V1
) -> tuple[str, dict[str, str], str]:
    """Validate a raw model response; return ``(gloss, distinction, surface)``.

    The response must be exactly one JSON object (surrounding whitespace is
    allowed; code fences or extra text are not) with exactly
    ``prompt.output_keys``. ``surface`` must equal ``utterance`` exactly.
    """
    if prompt.prompt_id not in DISTINCTION_KEYS:
        raise ExtractionError(f"no distinction key set registered for prompt {prompt.prompt_id!r}")
    if not isinstance(raw_output, str):
        raise ExtractionError(f"model output must be str, got {type(raw_output).__name__}")

    try:
        data = json.loads(raw_output, object_pairs_hook=_reject_duplicate_keys)
    except json.JSONDecodeError as e:
        raise ExtractionError(f"output is not a single JSON object ({e})") from e
    if not isinstance(data, dict):
        raise ExtractionError(f"output must be a JSON object, got {type(data).__name__}")

    expected = set(prompt.output_keys)
    if set(data) != expected:
        missing, extra = sorted(expected - set(data)), sorted(set(data) - expected)
        raise ExtractionError(f"output keys must be {sorted(expected)}; missing {missing}, unexpected {extra}")

    gloss, distinction, surface = data["gloss"], data["distinction"], data["surface"]

    if not isinstance(gloss, str) or not gloss.strip():
        raise ExtractionError(f"'gloss' must be a non-empty string, got {gloss!r}")

    if not isinstance(distinction, dict):
        raise ExtractionError(f"'distinction' must be an object, got {type(distinction).__name__}")
    allowed = DISTINCTION_KEYS[prompt.prompt_id]
    unknown = sorted(set(distinction) - allowed)
    if unknown:
        raise ExtractionError(f"'distinction' has unknown keys {unknown}; allowed {sorted(allowed)}")
    for key, value in distinction.items():
        if not isinstance(value, str) or not value.strip():
            raise ExtractionError(f"'distinction.{key}' must be a non-empty string, got {value!r}")
        closed = CLOSED_DISTINCTION_VALUES.get(key)
        if closed is not None and value not in closed:
            raise ExtractionError(f"'distinction.{key}' must be one of {sorted(closed)}, got {value!r}")

    if not isinstance(surface, str):
        raise ExtractionError(f"'surface' must be a string, got {type(surface).__name__}")
    if surface != utterance:
        raise ExtractionError(f"'surface' must equal the input utterance exactly; got {surface!r}, expected {utterance!r}")

    return gloss, distinction, surface


# --- lang_profile -----------------------------------------------------------

# Latin-script tokens counted as English in Latin-majority code-mixed text.
# Words that are also common romanized Hindi (e.g. "main", "the", "is", "to",
# "hi", "do", "us", "so", "me", "par") are deliberately excluded.
_ENGLISH_WORDS = frozenset(
    """
    and or but with for from about after before because please sorry thanks thank
    you your my our their his her its they we she he it this that what when where
    why how who will would can could should have has had was were are been being
    not yes okay ok today tomorrow yesterday tonight week weekend month year
    morning evening night time late early busy free good bad happy sad
    call phone mobile message email office meeting work job boss team manager
    salary bank money card app online order delivery shopping market
    home house flat room school college class exam project laptop computer
    friend friends birthday party doctor hospital train bus car ticket flight
    hotel trip plan movie lunch dinner breakfast coffee tea food restaurant gym
    shift aunty uncle cousin
    """.split()
)

_CJK_SCRIPTS = frozenset({"CJK", "HIRAGANA", "KATAKANA"})


def _char_script(ch: str) -> str | None:
    if not unicodedata.category(ch).startswith("L"):
        return None
    first = unicodedata.name(ch, "UNKNOWN").split()[0]
    return "CJK" if first in _CJK_SCRIPTS else first


def _token_script(token: str) -> str | None:
    scripts = Counter(s for s in map(_char_script, token) if s)
    return scripts.most_common(1)[0][0] if scripts else None


def _parse_lang_tag(lang: str) -> list[str]:
    parts = lang.lower().split("-")
    if not all(p.isalpha() and 2 <= len(p) <= 3 for p in parts) or len(set(parts)) != len(parts):
        raise ValueError(f"unsupported lang tag {lang!r}: expected e.g. 'hi' or code-mixed 'hi-en'")
    return parts


def derive_lang_profile(lang: str, utterance: str) -> dict[str, float]:
    """Deterministic language mix, following the fixture convention.

    - The probe's ``lang`` tag is authoritative for which languages occur: a
      single-language tag ``L`` gives ``{L: 1.0, "en": 0.0}`` (``{"en": 1.0}``
      for English), even if loanwords appear.
    - Code-mixed ``L-en`` tags give the share of English word tokens: in
      Latin-majority text a Latin token is English if it is in a small
      English word list; in other-script-majority text every Latin token is
      English. ``L`` gets the remainder.
    - ``script_mix`` is the share of word tokens not in the utterance's
      majority script (Han/Hiragana/Katakana count as one script).

    Values are rounded to 2 decimals.
    """
    langs = _parse_lang_tag(lang)
    tokens = [t for t in utterance.split() if _token_script(t)]
    scripts = [_token_script(t) for t in tokens]
    n = len(tokens)
    majority, majority_n = Counter(scripts).most_common(1)[0] if n else (None, 0)
    script_mix = round(1 - majority_n / n, 2) if n else 0.0

    if len(langs) == 1:
        (only,) = langs
        profile = {only: 1.0} if only == "en" else {only: 1.0, "en": 0.0}
    elif len(langs) == 2 and "en" in langs:
        other = langs[0] if langs[1] == "en" else langs[1]
        if majority == "LATIN":
            en_n = sum(
                1
                for t, s in zip(tokens, scripts)
                if s == "LATIN" and "".join(c for c in t if c.isalpha()).lower() in _ENGLISH_WORDS
            )
        else:
            en_n = scripts.count("LATIN")
        en = round(en_n / n, 2) if n else 0.0
        profile = {other: round(1 - en, 2), "en": en}
    else:
        raise ValueError(f"unsupported lang tag {lang!r}: only 'L' or 'L-en' code-mixing is supported")

    profile["script_mix"] = script_mix
    return profile


# --- building Extractions ---------------------------------------------------


def build_extraction(
    probe: ProbeItem,
    side: str,
    raw_output: str,
    *,
    backbone: str,
    seed: int,
    prompt: PromptTemplate = MEM0_EXTRACTION_V1,
) -> Extraction:
    """Validate ``raw_output`` for one probe side and build its ``Extraction``."""
    utterance = utterance_for(probe, side)
    try:
        gloss, distinction, surface = parse_model_output(raw_output, utterance=utterance, prompt=prompt)
    except ExtractionError as e:
        raise ExtractionError(
            str(e), pair_id=probe.pair_id, side=side, raw_output=raw_output
        ) from e
    return Extraction(
        pair_id=probe.pair_id,
        side=side,
        raw_output=raw_output,
        gloss=gloss,
        distinction=distinction,
        surface=surface,
        lang_profile=derive_lang_profile(probe.lang, utterance),
        backbone=backbone,
        prompt_id=prompt.prompt_id,
        seed=seed,
    )


def extract_many(
    items: Sequence[tuple[ProbeItem, str]],
    generator: TextGenerator,
    params: GenerationParams | None = None,
    *,
    prompt: PromptTemplate = MEM0_EXTRACTION_V1,
) -> list[Extraction]:
    """Extract ``(probe, side)`` items with one batched ``generate`` call.

    Returns Extractions in input order. If any item fails validation, raises
    ``ExtractionBatchError`` holding every failure (with raw output) and the
    successful Extractions.
    """
    params = params or GenerationParams()
    items = list(items)
    for probe, side in items:
        if not isinstance(probe, ProbeItem):
            raise TypeError(f"expected ProbeItem, got {type(probe).__name__}")
        utterance_for(probe, side)  # validates side
    if not items:
        return []

    prompts = [prompt.render(utterance_for(probe, side)) for probe, side in items]
    outputs = generator.generate(prompts, params)
    if not isinstance(outputs, list) or len(outputs) != len(items):
        got = len(outputs) if isinstance(outputs, list) else type(outputs).__name__
        raise ExtractionError(f"generator returned {got} outputs for {len(items)} prompts")

    extractions: list[Extraction | None] = []
    failures: list[ExtractionError] = []
    for (probe, side), raw in zip(items, outputs):
        try:
            extractions.append(
                build_extraction(
                    probe, side, raw, backbone=generator.backbone, seed=params.seed, prompt=prompt
                )
            )
        except ExtractionError as e:
            failures.append(e)
            extractions.append(None)
    if failures:
        raise ExtractionBatchError(failures, extractions)
    return extractions  # type: ignore[return-value]


def extract(
    probe: ProbeItem,
    side: str,
    generator: TextGenerator,
    params: GenerationParams | None = None,
    *,
    prompt: PromptTemplate = MEM0_EXTRACTION_V1,
) -> Extraction:
    """Extract one side of one probe; raises ``ExtractionError`` on bad output."""
    try:
        return extract_many([(probe, side)], generator, params, prompt=prompt)[0]
    except ExtractionBatchError as e:
        raise e.failures[0] from e
